[plugins]
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
# Paper API
paper = "1.21.1-R0.1-SNAPSHOT"
velocity = "3.3.0-SNAPSHOT"
minecraft = "1.21.1"

# Gradle Plugins
paperweight = "1.7.2"
runPaper = "2.3.0"
minotaur = "2.+"
shadow = "8.3.0"
hangar = "0.1.2"

# Bukkit Plugins
itemsadder = "3.6.3-beta-14"
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.6"
decentholograms = "2.8.8"
fancyholograms = "2.2.0"
worldguard = "7.0.10"
oraxen = "1.171.0"
nbtapi = "2.13.0"
vault = "1.7.1"

# Libraries
configurate = "4.2.0-SNAPSHOT"
jetbrains = "24.1.0"
adventure = "4.17.0"
vital = "2.0.1"

[libraries]
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

# Kyori
kyori-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
kyori-text = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
kyori-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Plugins
decent-holograms = { module = "com.github.decentsoftware-eu:decentholograms", version.ref = "decentholograms" }
fancy-holograms = { module = "de.oliver:FancyHolograms", version.ref = "fancyholograms" }
headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
itemsadder = { module = "com.github.LoneDev6:api-itemsadder", version.ref = "itemsadder" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }

# Libraries
jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

vital-paper = { module = "com.ryderbelserion.vital:paper", version.ref = "vital" }
vital-core = { module = "com.ryderbelserion.vital:core", version.ref = "vital" }

[bundles]
holograms = ["decent-holograms", "fancy-holograms"]
items = ["itemsadder", "oraxen"]